### ISSUE TITLE
Pages Widget: Update Design

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone#222] opened 2020-10-01 19:32 UTC
Current | Updated Design
------------ | -------------
![image](https://user-images.githubusercontent.com/2846578/94854699-4f79f780-03fb-11eb-9c30-c73000137f1d.png) | ![image](https://user-images.githubusercontent.com/2846578/94854679-47ba5300-03fb-11eb-849f-6a5f1547fab9.png)

[Figma mockups](https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=1272%3A386)

**Comment by kishanjasani** [comment] 2020-10-02 13:07
The issue is resolved in PR: #235

**Closed as completed** 2020-10-07 05:31 UTC
Labels: Good first issue, Help wanted, [Component] Default blocks, [Type] Task
