### ISSUE TITLE
Recent Posts Widget: Update Design

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone#219] opened 2020-10-01 19:08 UTC
Before | Updated Design
------------ | -------------
![image](https://user-images.githubusercontent.com/2846578/94852384-d0cf8b00-03f7-11eb-8358-df73605ef1cc.png) | ![image](https://user-images.githubusercontent.com/2846578/94852801-6bc86500-03f8-11eb-8079-9a322f952822.png)

[Mockups in Figma](https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=1272%3A386)

**Comment by kishanjasani** [comment] 2020-10-02 13:13
The issue is also resolved in PR: #235

**Closed as completed** 2020-10-07 05:31 UTC
Labels: Good first issue, Help wanted, [Component] Default blocks, [Type] Task
