### ISSUE TITLE
Bug quote block

### ISSUE THREAD

**Issue by naunha** [WordPress/twentytwentyone#763] opened 2020-10-31 12:37 UTC
When inserting a quote block, the quotation mark is in the wrong position, overlapping the text
![Captura de Tela (134)](https://user-images.githubusercontent.com/5017547/97779423-af7bcf00-1b5c-11eb-956f-276dc59c1d2a.png)

**Comment by aristath** [comment] 2020-11-03 10:25
Closing as duplicate of #759

**Closed as completed by aristath** 2020-11-03 10:25 UTC
