### ISSUE TITLE
Recent Comment Widgets: Update Design

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone#220] opened 2020-10-01 19:11 UTC
Current | Updated Design
------------ | -------------
![image](https://user-images.githubusercontent.com/2846578/94852589-1d1acb00-03f8-11eb-88e8-10eafac9b28d.png) | ![image](https://user-images.githubusercontent.com/2846578/94852858-7e429e80-03f8-11eb-8d5f-7b2bd9c3a5a2.png)

[Figma mockups](https://www.figma.com/file/OEtsCj8oD8JPVx4OvsS0U2/Twenty-Twenty-One?node-id=1272%3A386)

**Comment by kishanjasani** [comment] 2020-10-02 13:09
The issue is also resolved in PR: #235

**Closed as completed** 2020-10-07 05:31 UTC
Labels: Good first issue, Help wanted, [Component] Default blocks, [Type] Task
