### ISSUE TITLE
gallery image captions

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwentyone#560] opened 2020-10-16 20:07 UTC
The legacy gallery (shortcode) looks much better than the gallery block because of the treatment of the image captions.
I see these problems with the image captions on the gallery block:
1. The caption obscures the image.
![obscured](https://user-images.githubusercontent.com/7957680/96299576-e6c57a00-0fb9-11eb-913a-3017529b41a1.jpg)

2. Linked images with captions don't show the link cursor where the caption is. (If the caption covers the whole image, you can't open the link.) 
(this can be fixed with `pointer-events:none`)
![link-cursor](https://user-images.githubusercontent.com/7957680/96299388-9ea65780-0fb9-11eb-8af8-8c42b7b6107c.gif)

3. Captions on top of images create scrollbars, especially when more columns are used.
![six-columns](https://user-images.githubusercontent.com/7957680/96298761-9d285f80-0fb8-11eb-9cbd-1cbc60428363.jpg)

4. The caption styling can be bigger than the image. Note the at the end of the first row, where the caption styling is larger than the image itself.
![caption-background-on-small-image](https://user-images.githubusercontent.com/7957680/96298588-52a6e300-0fb8-11eb-967e-e705254de2f9.jpg)

-----------------
I think most of these style problems are actually in the block styles, but it's high time they were fixed!
Apart from the link problem, the other things can be fixed by not overlapping the image and caption. For reference, here is how the gallery shortcode looks, so much nicer:
![gallery-shortcode](https://user-images.githubusercontent.com/7957680/96303886-cc42cf00-0fc0-11eb-9487-3a4a0f450984.jpg)

**Comment by melchoyce** [comment] 2020-10-16 20:46
Duplicate of #238. The problem is caused by Gutenberg, so we've left it to be solved upstream.

**Closed as completed by melchoyce** 2020-10-16 20:46 UTC

**Comment by joyously** [comment] 2020-10-16 21:16
This issue that you are calling duplicate has 4 parts, and only the second part is a duplicate of that other issue, which appears that it didn't even get the correct fix (`pointer-events:none`).
