### ISSUE TITLE
Some elements aren’t visible on focus when the body background color is set to white  

### ISSUE THREAD

**Issue by briceduclos** [WordPress/twentytwentyone#864] opened 2020-11-22 13:57 UTC
**To Reproduce**

Inside the Customizer, open the Colors & Dark Mode panel and change Background Color to white. On focus, the text of the following elements are black on a black background:

- logo png transparent
- blog pagination
- social icons inside the footer
- link inside the footer (site title and WordPress)

![focus-white-bg](https://user-images.githubusercontent.com/56188815/99905698-c54f6080-2cd2-11eb-8992-960a17610a6a.jpg)

**Comment by carolinan** [comment] 2020-11-22 16:22
This has already been fixed twice... I am really not sure how this is issue is back.
Is this the current trunk version from GitHub or a version bundled with 5.6 RC?

**Comment by carolinan** [comment] 2020-11-23 07:13
For the newer/older post pagination it looks like the issue is when the link is activated, like when you hover and then click.
The text is not black on black when it is focused only.

**Comment by carolinan** [comment] 2020-11-24 14:30
I will close this, I believe it has been solved 🤞

**Closed as completed by carolinan** 2020-11-24 14:30 UTC
