### ISSUE TITLE
Additional Information: Weight + Dimension Alignment 

### ISSUE THREAD

**Issue by ldr2273** [WordPress/twentytwentyone#850] opened 2020-11-13 04:52 UTC
**Describe the bug**
Product Weight + Dimensions on Additional Information tab could be better spaced.

**To Reproduce**

1. Add a product with Weight + Dimensions.
2. Visit product page -> Additional information tab and see alignment:

![Alignment](https://d.pr/i/rBz4dw+)
Link: https://d.pr/i/rBz4dw

**Expected behavior**
Not real problematic, but stylistically could benefit from a bit more of a space there.

**Editor version (please complete the following information):**
- WordPress version: 5.6-beta4-49590
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? default

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome]
 - Version [86.0.4240.198]

- Atomic ephemeral
- WP: 5.6-beta4-49590
- WC: 4.7.0
- PHP: 8.0.0RC3

**Comment by carolinan** [comment] 2020-11-13 05:00
Hi, the default theme can not have styles for specific plugins, **because there is no way to support all plugins equally and fairly.**

From the screenshot, I will assume that this is WooCommerce?
I am not able to tell if this is a table, a list, or something else?

**Comment by carolinan** [comment] 2020-11-13 05:04
I was able to locate it at my own demo shop that I have created with the theme.
The problem is not related to the theme, but to the plugin that removes the default spacing that the theme uses for tables:

```
.woocommerce table.shop_attributes td {
    font-style: italic;
    padding: 0;
    border-top: 0;
    border-bottom: 1px dotted rgba(0,0,0,.1);
    margin: 0;
    line-height: 1.5;
}
```

Because of this, I am closing the issue.

**Closed as completed by carolinan** 2020-11-13 05:04 UTC

**Comment by ldr2273** [comment] 2020-11-13 06:08
@carolinan - Thank you! Yes, I forgot to mention this was when using WC but glad you were able to confirm for me.
