### ISSUE TITLE
Navigation Block: Background should be transparent by default

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyone#679] opened 2020-10-23 19:52 UTC
**Describe the bug**
When I add a Navigation block, it automatically includes a background color. This presents a problem when you're putting the block inside of a container with a different background color.

**To Reproduce**
1. Create a new post or page.
2. Add a group block, and change the background color.
3. Add a navigation block inside of that group block.
4. See that the navigation block provides its own background color.

**Screenshots**
![image](https://user-images.githubusercontent.com/2846578/97047482-0bd06480-1547-11eb-9967-04172d6e8eb2.png)
![image](https://user-images.githubusercontent.com/2846578/97047503-168af980-1547-11eb-9a60-1444c86b851c.png)

**Expected behavior**
I expect the navigation block background to be transparent, and the text color to adapt based on the tint or shade of the container's background color:

![image](https://user-images.githubusercontent.com/2846578/97047716-5eaa1c00-1547-11eb-85dd-7414024601c6.png)
![image](https://user-images.githubusercontent.com/2846578/97047830-8c8f6080-1547-11eb-8291-1f7fce4cd7dd.png)

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Gutenberg version: 9.2.1

**Desktop (please complete the following information):**
OS: macOS 10.15.6
Browser: Chrome 86.0.4240.80 (Official Build) (x86_64)

**Comment by carolinan** [comment] 2020-10-23 23:13
Because this is a Gutenberg only block, not included in 5.6 this is a low priority.

**Comment by aristath** [comment] 2020-10-26 11:35
Actually a few months ago I tried to do that and had a PR merged in Gutenberg: https://github.com/WordPress/gutenberg/pull/24462
However it introduced a regression and was later reverted in https://github.com/WordPress/gutenberg/pull/24763
The problem there is submenu backgrounds:

<img width="435" alt="Screenshot 2020-08-21 at 1 32 29 pm" src="https://user-images.githubusercontent.com/677833/90855727-db3b4580-e3b2-11ea-995f-3df8f5866978.png">

I think this is something that should be fixed in Gutenberg and not the theme... @melchoyce if you have any ideas on how to improve the implementation in Gutenberg we can make a pull-request there and fix it for all themes (because I agree, the current implementation is far from perfect and confusing) :+1:

**Comment by karmatosed** [comment] 2020-10-27 09:34
@aristath can I check my understanding of what you are asking? I'm just coming to this to bring some context regarding backgrounds on navigation blocks specifically. What I think is being recommended would be for backgrounds to not be set? If that is the case, there is a situation where the default is a transparent background, which means that the default experience could be less than ideal for someone, or if it wasn't styled.

I wonder, how can both it be made less troublesome for theme styling, but have great defaults out of the box? Would love to work on that and get an issue going.

**Comment by melchoyce** [comment] 2020-10-27 14:00
The problem @aristath encountered when removing the background from navigation menus is that then submenus don't have a background either, which causes the overlap you can see in that screenshot.

**Comment by karmatosed** [comment] 2020-10-27 16:08
@melchoyce thanks for clarifying, I think therefore if I am right there needs to be a decision on if things all have a background or all don't?

**Comment by melchoyce** [comment] 2020-10-27 16:17
What I really want is for the block to inherit the background color of its container. So if you drop a navigation block into a group block with a purple background, the navigation block and its submenus are also purple.

**Comment by aristath** [comment] 2020-10-27 16:26
> What I really want is for the block to inherit the background color of its container. So if you drop a navigation block into a group block with a purple background, the navigation block and its submenus are also purple.

Yeah, that was the intention of my Gutenberg PR too...
After a long discussion on Slack back then, a solution that was suggested was to use CSS-variables in blocks (it's also mentioned in the PR comments). So for example when you select a background color in a group, it will get `style="--background-color: #c00;"`. That property would then be usable by all internal styles for the block itself, as well as all its children. So if there was a nav block inside that group block, it would automatically use the `--background-color` of its parent. If the nav block had a background-color, then it would get a style too, and that would automatically override the parent element's property.

A PR with that suggestion was submitted on https://github.com/WordPress/gutenberg/pull/24757 and was later closed (there's a discussion on that ticket if anyone's interested)

**Comment by carolinan** [comment] 2020-11-02 13:00
At this time there does not seem to be a solution for this, and it would first need to be solved in the editor/Gutenberg.

**Closed as completed by carolinan** 2020-11-02 13:00 UTC
Labels: [Type] Bug, [Component] Default blocks

**Comment by joyously** [comment] 2020-11-02 14:18
Can't the top level nav use `background-color: inherit` and the submenus use the CSS variable?
