### ISSUE TITLE
Desktop Menu: It's not always possible to access the submenus on hover. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentytwentyone#375] opened 2020-10-08 19:35 UTC
When hovering over top-level parent menu items, it's sometimes difficult to access the children: 

![hover](https://user-images.githubusercontent.com/1202812/95505109-d12dd000-097b-11eb-8677-577a173f34d7.gif)

Tested in Safari v14.0.
MacOS 10.15.6.

**Comment by carolinan** [comment] 2020-10-08 20:03
This is probably because we had to move the sub menu down to make the full focus outline of the parent visible.

**Comment by carolinan** [comment] 2020-10-09 03:53
I am able to reproduce this on Chrome on win10.

**Comment by aristath** [comment] 2020-10-09 05:17
Assigned this one to myself, it is caused by a 3px offset added in https://github.com/WordPress/twentytwentyone/pull/329

**Closed as completed** 2020-10-09 18:24 UTC
Labels: [Type] Bug, High priority
