### ISSUE TITLE
Block editor: Social icons aren’t correctly aligned

### ISSUE THREAD

**Issue by briceduclos** [WordPress/twentytwentyone#716] opened 2020-10-27 23:50 UTC
**Describe the bug**
When trying to create a list with 2 social icons using the Social Icons block, the icons aren’t aligned inside the editor. 

**To Reproduce**
Inside the code editor, paste the following code:

```
<!-- wp:social-links -->
<ul class="wp-block-social-links"><!-- wp:social-link {"url":"#","service":"wordpress"} /-->

<!-- wp:social-link {"url":"#","service":"github"} /--></ul>
<!-- /wp:social-links -->
```

**Screenshots**

Block not focused:
![social-icons](https://user-images.githubusercontent.com/56188815/97373885-40ca1780-18b7-11eb-957b-c2be3d653119.PNG)

Block focused:
![social-icons-focus](https://user-images.githubusercontent.com/56188815/97373884-40318100-18b7-11eb-991a-a47a9a03b924.PNG)

**Comment by carolinan** [comment] 2020-10-28 08:58
@briceduclos I'd love to know what WordPress version this is on and if/what version of Gutenberg that is active.

This issue has been brought up and has been fixed once 🤔 https://github.com/WordPress/twentytwentyone/issues/203

**Comment by carolinan** [comment] 2020-10-28 09:05
Ugh, would love confirmation on if this is intended, that the block was remade to only add items when you actively choose to click the plus icon after the 3 colored dots.

**Comment by carolinan** [comment] 2020-10-28 09:08
So, after actively adding the social links, I am not able to reproduce the problem in the issue above:

![social](https://user-images.githubusercontent.com/7422055/97415388-70a00c00-1905-11eb-9341-690bcbe12d46.png)

(Gutenberg is not active)

**Comment by aristath** [comment] 2020-10-28 09:16
I can replicate using WordPress 5.5.1 (stable) + Gutenberg master branch.

**Comment by briceduclos** [comment] 2020-10-28 10:21
@carolinan The issue only happens when you add 2 social icons (with 3, 4, 5 icons, the alignment is correct). 
I'm using WordPress 5.6-beta2, Gutenberg isn't active.

**Closed as completed** 2020-10-29 07:28 UTC
Labels: [Type] Bug, Needs testing, [Component] Default blocks, Low priority
