### ISSUE TITLE
Improving the look of Twenty Twenty-One when a site has very little content

### ISSUE THREAD

**Issue by carike-codes** [WordPress/twentytwentyone#167] opened 2020-09-28 19:30 UTC
The critical success factor (in my personal view) for a bundled theme is how it handles it when a site has very little content.
I switched a test site from Twenty Twenty to Twenty Twenty-One.
I'm attaching screenshots of the results.

This issue does not refer to starter content :) 

![image (13)](https://user-images.githubusercontent.com/58555331/94477111-ba47ea80-01d1-11eb-9a8b-dbfaad71a001.png)
![image (14)](https://user-images.githubusercontent.com/58555331/94477110-ba47ea80-01d1-11eb-874c-3d41d625ccb0.png)
![image (15)](https://user-images.githubusercontent.com/58555331/94477106-b87e2700-01d1-11eb-8b8a-d18f2b719f70.png)

**Comment by melchoyce** [comment] 2020-09-28 21:17
Hey @carike-codes! Thanks for taking these screenshots. Do you have any specific suggestions we could implement?

**Comment by carike-codes** [comment] 2020-09-28 21:47
Still thinking about it 🤐 Really not sure.

My background stayed white after activating Twenty Twenty-One. I had to go to the Customizer, first click to change colour and then Default before it changed. I'm not sure why that is? It already looks better in the default colour (attached screenshot).

![image](https://user-images.githubusercontent.com/58555331/94488826-aa390680-01e3-11eb-8066-b817e01fd95f.png)

I have a number of pages, but the menu isn't showing up by default after switching themes?

The H1 header size seems a bit overwhelming when content is sparse.
Perhaps if it was smaller?
Also, perhaps an outline around the whole element, not just underline? That could break up the section from the site title and the site's description?
I realize it is difficult to create nice visuals when you just have text and no images to work with.

Moving the default widget area to a sidebar also seems like it would help make things look less empty.

**Comment by carike-codes** [comment] 2020-09-29 06:23
Something that came to mind this morning is changing the H1 headers to a font that resembles impressionist techniques by default? That may perhaps help with creating natural "sections" on pages without images?
The theme could then offer a modern/casual option for the font styling?

Something else that came to mind is to style boxes similar to the look of the search bar as a visual element if the page does not contain any photos (so, for example, three boxes with a thick navy outline, filled with a white background, possibly overlapping slightly).

Attaching screenshots of Steve's test site. His site has quite a lot more content (he was performing unit tests), but the front page is still very text-heavy. I expect that this would be the case for a very large number of sites, as quality free images to complement your content can be very hard to find.

![image](https://user-images.githubusercontent.com/58555331/94518353-0fafe600-022a-11eb-84b1-a43d2eafe457.png)
![image](https://user-images.githubusercontent.com/58555331/94518470-42f27500-022a-11eb-83fd-6f0a7df426c7.png)
![image](https://user-images.githubusercontent.com/58555331/94518646-64536100-022a-11eb-9473-5ce3b20cc6cf.png)
![image](https://user-images.githubusercontent.com/58555331/94519090-81882f80-022a-11eb-91f3-39e88230db87.png)
![image](https://user-images.githubusercontent.com/58555331/94519287-9d8bd100-022a-11eb-8035-88cafd9911d2.png)

Perhaps the number of items for category (and other widgets) should be limited by default?
A very large number of categories would also look better in a sidebar than in a widget at the bottom of the page.

**Comment by pattonwebz** [comment] 2020-09-29 09:16
> Something that came to mind this morning is changing the H1 headers to a font that resembles impressionist techniques by default?

This theme uses only system fonts for performance, simplicity and readability. Can you suggest a system font which might look like you wanted?

**Comment by carike-codes** [comment] 2020-09-29 09:33
:wave:
Hallo, William.

I've just been thinking of ideas for how to create "visual" elements for an entirely text-based site. I haven't looked at specific fonts yet. Do you perhaps have a link handy with examples of the available system fonts?

It is kind of difficult to explain the "picture" I have in mind. I was thinking of a "thicker" font (something sort of like Impact), but with a "shading" / texture to the colour that creates an impressionist / brush-stroke feel.

**Comment by pattonwebz** [comment] 2020-09-29 09:50
Hey Carike 👋  

I'm afraid I can't see any [cross compatible system fonts](https://blog.hubspot.com/website/web-safe-html-css-fonts) that gives the type of effect that your after :(. I think it would need to be a web font of some kind but the theme doesn't have any setup to include one in the base theme.

We probably have to think up other ways to give some flair to the longer text sections - via content of the posts is the best option really as there is limited visual effects for us to use on the general text :(

**Comment by carike-codes** [comment] 2020-09-29 10:21
This StackExchange question adds texture to the font using an image for the colour. I'm not sure if something like this is possible?
https://tex.stackexchange.com/questions/510458/can-i-color-text-by-using-an-image-so-that-the-color-isnt-flat
![image](https://user-images.githubusercontent.com/58555331/94545642-18fe7a00-024d-11eb-8a67-0e0dff80e8c2.png)
A brush-texture navy should work nicely with the default colour in this image:
![image](https://user-images.githubusercontent.com/58555331/94545940-7c88a780-024d-11eb-9566-3f74a60df39a.png)
So the image used to create the colour texture might look something like this:
![image](https://user-images.githubusercontent.com/58555331/94546137-c4a7ca00-024d-11eb-8a50-66e258d8661d.png)
or something like this:
![image](https://user-images.githubusercontent.com/58555331/94546238-e5701f80-024d-11eb-8348-8d6c2c94378b.png)
Those are just random images. Would need to look for ones with GPL-compat licenses, or perhaps one of the designers on the project might be able to create a custom image for us.

For a more modern look (think Steve's site with the sneaker logo), that Hubspot page actually breaks the text up nicely by using an outline and different background colour for the headers.
![image](https://user-images.githubusercontent.com/58555331/94544081-1b5fd480-024b-11eb-96b9-81767035350d.png)

**Comment by paaljoachim** [comment] 2020-09-29 19:42
I just got to say this is a very interesting issue.... something along the lines of how can we have prettier (system) fonts that fit in with the mood/style of the site.

**Comment by carike-codes** [comment] 2020-10-01 06:14
:wave:
Nice to see you, Paal!

Yes. The one question is: "How can we colour system fonts to create the illusion of depth and create consistent styling?"
I think there is another though? "How can we use blocks themselves as decorative? (Borders, fill, etc.)"

Another option may be to add quasi-images in the form of patterns.

Just one example: The blog page may benefit from repeating (groups of) tile patterns on each side (if a sidebar is not going to be considered).
Perhaps something like this, but styled to suit the mood of the site (for now, let's say Impressionist or Modern).
![image](https://user-images.githubusercontent.com/58555331/94774357-08214600-03be-11eb-9133-b9ca6f01bb78.png)

**Comment by joyously** [comment] 2020-10-01 14:03
text-shadow
box-shadow
gradients
masking http://thenewcode.com/1032/Easy-Cross-Browser-Text-Masks-with-Blend-Modes

Some feedback I had on my own theme was that it was too hard to read the text because of shadows and gradients(and there isn't that much), but this was from someone who is partially color-blind and so everything looked a bit blurry. If you put a lot of lines (borders, underlines), it's hard to find the links and it looks really "busy".

I think whatever the design is, it should work for all pages, whether they are just text or not. Sites with very little content will not look like much with _any_ theme.

**Comment by helen** [comment] 2020-10-01 20:45
Do you think that the issue is about how the theme shows their existing content or is it more about how they see the new theme working for future content?

**Comment by melchoyce** [comment] 2020-10-16 01:17
Since this issue is pretty broad I'm going to close it up, but if there's anything specific that needs to still be addressed, please add a new issue. Thanks!

**Closed as completed by melchoyce** 2020-10-16 01:17 UTC
Labels: [Type] Discussion
