### ISSUE TITLE
Home page being the latest posts

### ISSUE THREAD

**Issue by naunha** [WordPress/twentytwentyone#195] opened 2020-09-30 21:33 UTC
Is it possible that, if the home page is chosen, the display of the latest posts, that these posts are displayed in summary form, instead of all the content? I'm new to github, but I'm really excited about this new theme. Thank you

**Comment by naunha** [comment] 2020-09-30 21:43
I think that this topic has already been addressed in this topic, excuse me - Add option to use excerpts on posts page (https://github.com/WordPress/twentytwentyone/issues/129)

**Comment by carolinan** [comment] 2020-10-01 07:36
Hi, thank you for your suggestion, I will close this, since it is a duplicate of the post you mentioned.

**Closed as completed by carolinan** 2020-10-01 07:36 UTC
Labels: [Status] Duplicate
